url: "https://stanmx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "amazingcovers" # the subpath of your site, e.g. /blog
title: "Amazing Covers" # the name of your site, e.g. ACME Corp.
timezone: UTC
